BoxLayout:
    orientation: 'vertical'

    BoxLayout:
        orientation: 'horizontal'
        TextInput:
            text: '34'

        BoxLayout:
            size_hint_x: 0.25
            orientation: 'vertical'
            Button:
                size_hint_y: 0.5
                text: 'Up'
            Button:
                size_hint_y: 0.5
                text: 'Down'

    Button:
        text: 'Convert m to km'
    Label:
        text: '54.717'
        color: (1,1,0,1)